### ISSUE TITLE
GNU Recutils

### ISSUE THREAD

**Issue by KarlLevik** [Vettabase/awesome-innovative-databases#1]
Does GNU Recutils qualify as innovative?
https://www.gnu.org/software/recutils/

They're certainly easy to use for people who just want to have a simple database based on text files, and not wanting to learn complicated query languages. Probably not great for huge volumes of data but good enough otherwise.

**Comment by federico-razzoli** [comment]
I don't consider it innovative because I think that simple text databases are very old, but I might miss something.

You can propose it as an external contribution. Create a `contrib` dicretory with a `gnu-recutils` file in it, which contains a project description and links.

**Comment by KarlLevik** [comment]
Indeed, it's not a new concept. 

No, that's fine, I'll close this.
